name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
      - 'feature-**'

jobs:

  test_phaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          cargo binstall cargo-nextest --secure
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      # - name: Lint
      #   run: |
      #     cd phaser
      #     make lint

      - name: Test
        run: |
          cd oxide
          make check
          make test
  # build_phaser:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build Docker
  #       run: |
  #         make docker
  #     - name: Docker image info
  #       run: |
  #         docker images
